#!/bin/sh

DIR=$1
TARGET=$2

if [ -z "$DIR" ]; then
	echo "No source directory provided"
	exit 1
fi
if [ -z "$TARGET" ]; then
	echo "No target directory provided"
	exit 1
fi

ARG=""
for file in $PWD/$DIR/*.meld; do
	base=`basename $file .meld`
	ARG="$ARG $file $PWD/$TARGET/$base"
done
compile-file $ARG
