
TARGET = /usr/local

install:
	mkdir -p $(TARGET)/bin
	install --mode=555 compile-file $(TARGET)/bin/
	install --mode=555 compile-directory $(TARGET)/bin/
	install --mode=555 compile-from-directory $(TARGET)/bin/
