#!/bin/sh

DIR=$1
TARGET=$2

if [ -z "$DIR" ]; then
	echo "No source directory provided"
	exit 1
fi
if [ -z "$TARGET" ]; then
	echo "No target directory provided"
	exit 1
fi

should_be_recompiled()
{
   if [ "$1" -nt "$2" ]; then
      return 0
   else
      if [ $(du -k $1 | cut -f1) -gt 50 ]; then
         return 1
      fi
      for subfile in $(grep 'include #' $1|awk -F '#' '{print $2}'); do
         filepath="$dir/$subfile"
         if should_be_recompiled "`dirname $1`/$subfile" $2; then
            return 0
         fi
      done
   fi
   return 1
}

ARG=""
for file in $PWD/$DIR/*.meld; do
   base=$(basename $file .meld)
   target="$TARGET/$base.m"
   if should_be_recompiled $file $target; then
      ARG="$ARG $file $PWD/$TARGET/$base"
      echo ">> Compiling $DIR/$base.meld to $target"
   fi
done
if [ -z "$ARG" ]; then
   echo ">> Files are up-to-date"
else
   meld-compile-file $ARG
fi
